Forgot username page, account directory configs
CSE416-MapHub/MapHub pull request #29
Opened 2023-11-14 05:54 UTC by wesleymui

2023-11-14 06:50 UTC, wilgao09 requested changes
In the forgotten user name form, you have a TODO to navigate to another page; maybe add a dummy page that just says "Reset email sent to [email]", or some indication that something happened. Additionally, have @EdwardNgg take a look at changes made to the main page.

2023-11-14 16:30 UTC, EdwardNgg requested changes
Everything other than the Home page looks fine. Preferably, we keep styling outside of JSX components so here is a single source for styles. Also, the NavBar is rendered on each page because it's in the app layout. Removing the IDs and changing the hrefs without modifying the component tests will break it. The tests rely on identifying components from their IDs.

2023-11-14 16:30 UTC, EdwardNgg commented on client/src/app/page.tsx
> +        {/* TODO: Add NavBar here */}
The NavBar rests on the app layout so it's rendered for each page.

2023-11-14 16:30 UTC, EdwardNgg commented on client/src/app/page.tsx
> +        sx={{
Preferably, we keep styling outside of JSX components so there's a single source for styles

2023-11-14 16:30 UTC, EdwardNgg commented on client/src/app/page.tsx
> +            A Complete <br/>
We don't need breaks because the box would automatically break and resize. Although, I'm not sure if it would look correct on different screen sizes.

2023-11-14 16:30 UTC, EdwardNgg commented on client/src/app/page.tsx
> -          <Link id="hero-discover" href="/discover">
Removing the Ids and changing the hrefs without changing the tests would break them.

2023-11-15 02:07 UTC, wilgao09 approved these changes
lgtm

2023-11-15 02:23 UTC, EdwardNgg approved these changes

2023-11-15 02:25 UTC, merged